### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by fawdlstty** [RimoChan/steal_piano#4]
piano.py加了一行调用然后直接运行输出：

```
E:\GitHub\steal_piano>python piano.py
Traceback (most recent call last):
  File "piano.py", line 15, in <module>
    @disk_cache('./dc')
  File "D:\Software\Python\Python38-32\lib\site-packages\rimo_utils\cache.py", line 39, in disk_cache
    dump, load, ext = 协议[protocol]
KeyError: './dc'
```
python：3.8.2
os：win11 21H2

**Comment by RimoChan** [comment]
库更新了这个忘记改了……
我来更新1下。

**Comment by RimoChan** [comment]
修好啦！
还有需要重新`pip install -r requirements.txt`。

**Comment by fawdlstty** [comment]
虽然但是，requirements.txt不全
```
Traceback (most recent call last):
  File "piano.py", line 64, in <module>
    ember('', 'fawdlstty', days=3000, save_path='1.png')
  File "piano.py", line 61, in ember
    nx.draw_kamada_kawai(G, nodelist=d.keys(), node_size=[v * 75 for v in d.values()], with_labels=True)
  File "D:\Software\Python\Python38-32\lib\site-packages\networkx\drawing\nx_pylab.py", line 1269, in draw_kamada_kawai
    draw(G, kamada_kawai_layout(G), **kwargs)
  File "D:\Software\Python\Python38-32\lib\site-packages\networkx\drawing\layout.py", line 709, in kamada_kawai_layout
    pos = _kamada_kawai_solve(dist_mtx, pos_arr, dim)
  File "D:\Software\Python\Python38-32\lib\site-packages\networkx\drawing\layout.py", line 721, in _kamada_kawai_solve
    import scipy as sp
ModuleNotFoundError: No module named 'scipy'
```

**Comment by RimoChan** [comment]
好吧，我又加上了……
