### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Undertone0809** [RimoChan/steal_piano#7]
运行日志如下：

```
34it [00:12,  2.67it/s]
Traceback (most recent call last):
  File "E:/Programming/githubhub/steal_piano/piano.py", line 67, in <module>
    ember('xxxxxxx', 'xxxxxx', save_path="aaaa.png")
  File "E:/Programming/githubhub/steal_piano/piano.py", line 39, in ember
    for i in tqdm(星表(我)):
  File "D:\Programming\Python\Python3.7\lib\site-packages\rimo_storage\cache.py", line 36, in 假func
    map[名字] = s
  File "D:\Programming\Python\Python3.7\lib\site-packages\rimo_storage\__init__.py", line 104, in __setitem__
    return super().__setitem__(k, self.serialize(v))
  File "D:\Programming\Python\Python3.7\lib\multiprocessing\synchronize.py", line 101, in __getstate__
    context.assert_spawning(self)
  File "D:\Programming\Python\Python3.7\lib\multiprocessing\context.py", line 356, in assert_spawning
    ' through inheritance' % type(obj).__name__
RuntimeError: RLock objects should only be shared between processes through inheritance

Process finished with exit code 1
```
应该是你的`rimo_storage` 产生的问题？这个报错是由 multiprocessing 模块抛出的，意味着在多进程环境下出现了问题。根据 traceback，问题发生在缓存模块 rimo_storage 中的 `_好dict.__setitem__ ` 方法中。这个缓存模块使用了 multiprocessing 中的 RLock 对象，但是 RLock 对象不能够在多进程环境下直接共享，只能够通过继承来共享。

**Comment by Undertone0809** [comment]
当然注释掉缓存是可以正常运行的。

**Comment by RimoChan** [comment]
咦，奇怪，我这代码里没有多进程啊

**Comment by Undertone0809** [comment]
这么抽象吗，我尝试rimo-storage==1.3.2和rimo-storage==1.3.3都存在这个问题

**Comment by RimoChan** [comment]
怪起来了，我自己试了一遍，没有这个问题啊。你是在什么环境下运行的？

**Comment by Undertone0809** [comment]
我是win10，python3.7的环境

**Comment by RimoChan** [comment]
那你运行的命令是什么？

**Comment by Undertone0809** [comment]
是的，我在piano.py下面加了几行就直接运行了 piano.py了
![image](https://user-images.githubusercontent.com/72488598/224324338-3273f325-f85b-4b91-a798-869043b20147.png)

**Comment by RimoChan** [comment]
等一下，为什么你的plt.savefig(save_path)在66行？它应当在62行

**Comment by Undertone0809** [comment]
哈哈哈哈没事，我加了点无关的空行

**Comment by RimoChan** [comment]
对了，直接运行是什么意思，指的是`python piano.py`吗？

**Comment by Undertone0809** [comment]
是的，我用pycharm直接运行的，它应该是等价于`python piano.py`的

**Comment by RimoChan** [comment]
好，我重装了一遍依赖以后找到问题了，是新版的PyGithub有问题。我给依赖降级了，你重新`pip install -r requirements.txt`一次就可以运行了。

**Comment by Undertone0809** [comment]
好的，感谢大佬！

**Comment by Undertone0809** [comment]
我想问一下`ember()` 函数中的token是必须的吗，好像没有token也可以得到相同的信息诶。

**Comment by RimoChan** [comment]
如果你的仓库的star数比较少的话，没有token也是可以的……

**Comment by Undertone0809** [comment]
如果是想获取别人用户的星图的话，用自己的token有用吗哈哈哈哈

**Comment by RimoChan** [comment]
有！

**Comment by Undertone0809** [comment]
嘿嘿懂啦，感谢！
